#
# TOML config file for the stand-alone Zal text parser
#

title = "Zal wordform generator"

[paths]
db_path_windows = 'C:\git-repos\Zal\Zal-Data\ZalData\ZalData_Master_full.db3'
db_path_linux = '/home/konstantin/zal/ZalData_demo.db3'
